# Generated by Django 5.2.1 on 2025-05-16 11:15

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnonymousFeedback',
        ),
        migrations.DeleteModel(
            name='TravelForm',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='user',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_date',
            field=models.DateField(default=datetime.date(2025, 5, 16)),
            preserve_default=False,
        ),
    ]
