# Generated by Django 5.2.1 on 2025-05-16 13:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_delete_anonymousfeedback_delete_travelform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='user',
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='chatbot.employee'),
            preserve_default=False,
        ),
    ]
